version: "3.1"

services:
  mongo:
    image: mongo
    container_name: server-monitor-mongo-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: server-monitor

  mongo-express:
    image: mongo-express
    container_name: server-monitor-mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://server-monitor-mongo-db:27017
    ports:
      - "8081:8081"
